### ISSUE TITLE
Grid mention sample is not working

### ISSUE THREAD

**Issue by TinaT2** [linkedin/Spyglass#109] opened 2020-12-30 05:08 UTC
What's the problem? Can we use the editor and recycler view separately or it has a problem like its sample?

**Comment by nhibner** [comment] 2020-12-30 05:14
@TinaT2 just tested the grid suggestions sample, it appears to be working as expected. Can you please provide more details on what exactly isn't working?

**Comment by nhibner** [comment] 2021-01-05 17:58
Closing this since more detailed information on why this sample is not working has not been provided, and at a glance, it appears to be working as intended. Please feel free to reopen if you can provide more details on the issue you're seeing, thanks.

**Closed by nhibner** 2021-01-05 17:58 UTC
